/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package JGUI;

import Controller.RentController;
import Database.CustomerDAO;
import Item.Game;
import Item.Item;
import Item.Mobil;
import Item.Motor;
import Item.Movie;
import User.Customer;
import java.sql.SQLException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author rahma
 */
public class CustomerItemDetail extends NavigatableJFrame{

    /**
     * Creates new form CustomerItemDetail
     */
    public CustomerItemDetail() {
        initComponents();
        this.setTitle("Item Detail");
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }
    public CustomerItemDetail(Item item) {
        initComponents();
        this.item = item;
        String itemName = "";
        System.out.println(item.getClass().toString());
        switch (item.getClass().toString()){
            case "class Item.Mobil":
                // Do in case mobil
                Mobil mobil = (Mobil) item;
                itemName = mobil.getModel();
                break;
            case "class Item.Game":
                // Do in case Game
                Game game = (Game) item;
                itemName = game.getTitle();
                break;
            case "class Item.Motor":
                // Do in case Motor
                Motor motor = (Motor) item;
                itemName = motor.getModel();
                break;
            case "class Item.Movie":
                // Do in case Movie
                Movie movie = (Movie) item;
                itemName = movie.getTitle();
                break;
        }
        
        this.namaBarang.setText(itemName);
        this.labelDeskripsi.setText(item.getDescription());
        this.LabelBiaya1.setText(LabelBiaya1.getText()+String.valueOf(item.getRentalChargePerDay()));
        this.setTitle("Item Detail");
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ActionButton = new javax.swing.JButton();
        TotalPaymentLabel = new javax.swing.JLabel();
        labelDeskripsi = new javax.swing.JLabel();
        namaBarang = new javax.swing.JLabel();
        StartDateChooser = new com.toedter.calendar.JDateChooser();
        EndDateChooser = new com.toedter.calendar.JDateChooser();
        LabelBiaya1 = new javax.swing.JLabel();
        DaysLabel = new javax.swing.JLabel();
        ToLable = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        ActionButton.setText("Rent Item");
        ActionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActionButtonActionPerformed(evt);
            }
        });

        TotalPaymentLabel.setText("Total payment:");

        labelDeskripsi.setText("Deskripsi:");

        namaBarang.setText("nama barang");

        StartDateChooser.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                StartDateChooserFocusLost(evt);
            }
        });

        EndDateChooser.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                EndDateChooserFocusLost(evt);
            }
        });

        LabelBiaya1.setText("Rent: Rp. /day");

        DaysLabel.setText("Days:");

        ToLable.setText("To:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(165, 165, 165)
                .addComponent(namaBarang)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LabelBiaya1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelDeskripsi)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(TotalPaymentLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(StartDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ToLable)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(EndDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(DaysLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ActionButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(20, 20, 20))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(namaBarang))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(labelDeskripsi)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EndDateChooser, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(LabelBiaya1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(StartDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(ToLable)
                                .addGap(2, 2, 2))))
                    .addComponent(DaysLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ActionButton)
                    .addComponent(TotalPaymentLabel))
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void ActionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActionButtonActionPerformed
        // TODO add your handling code here:
        Customer Account = (Customer) Application.Application.getAccount();
        if(this.ActionButton.getText().equals("Ok")){
            this.dispose();
            Application.Application.getMainMenu().show();
        }else if (this.ActionButton.getText().equals("Rent Item")){
            try {
                RentController.rent(Account, item, this.StartDateChooser.getDate(), this.EndDateChooser.getDate());
                new CustomerDAO().updateData(Account);
            } catch (SQLException ex) {
                Logger.getLogger(CustomerItemDetail.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        System.out.println(Account.getRentedItem().size());
        this.dispose();
        
    }//GEN-LAST:event_ActionButtonActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_formWindowClosed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        System.out.println(this.item.getItemID());
        //tempdata
        Customer account = (Customer) Application.Application.getAccount();
        if(account.getRentedItem().stream().filter(o -> o.getItemID()== this.item.getItemID()).findFirst().orElse(null) != null ){
            this.ActionButton.setText("Ok");
            System.out.println("you have this item");
        }else{
            this.ActionButton.setText("Rent Item");
            System.out.println("you don't have this item");
        }
        
        
    }//GEN-LAST:event_formWindowActivated

    private void StartDateChooserFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_StartDateChooserFocusLost
        // TODO add your handling code here:
        refresh();
    }//GEN-LAST:event_StartDateChooserFocusLost

    private void EndDateChooserFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_EndDateChooserFocusLost
        // TODO add your handling code here:
        refresh();
    }//GEN-LAST:event_EndDateChooserFocusLost
    public void refresh(){
        this.DaysLabel.setText("" + RentController.GenerateDayOfRent(this.StartDateChooser.getDate(), this.EndDateChooser.getDate()));
        this.TotalPaymentLabel.setText("" + RentController.GenerateTotalPayment(this.item, Integer.valueOf(this.DaysLabel.getText())));
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerItemDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerItemDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerItemDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerItemDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerItemDetail().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ActionButton;
    private javax.swing.JLabel DaysLabel;
    private com.toedter.calendar.JDateChooser EndDateChooser;
    private javax.swing.JLabel LabelBiaya1;
    private com.toedter.calendar.JDateChooser StartDateChooser;
    private javax.swing.JLabel ToLable;
    private javax.swing.JLabel TotalPaymentLabel;
    private javax.swing.JLabel labelDeskripsi;
    private javax.swing.JLabel namaBarang;
    // End of variables declaration//GEN-END:variables
    private Item item;
}
